### ISSUE TITLE
OAuth using python plugin

### ISSUE THREAD

**Issue by rajyraman** [MicrosoftDocs/dataexplorer-docs#1346]
Since I am having issues connecting to Dataverse using Managed Identity (#1322), I thought I will try raw python script to get the token. Below is the KQL code. This works fine in Jupyter Notebook.

````python
// set query_python_debug;
print '' | evaluate python(
typeof(access_token: string), 
```
import requests
import json
result = df
token_req_payload = {
	'grant_type': 'client_credentials',
	'scope': kargs["scope"],
	'client_secret': kargs["secret"],
	'client_id': kargs["client_id"]
}
token_response = requests.post(kargs["authUrl"],
data=token_req_payload)
		 
if token_response.status_code == 200:
	tokens = json.loads(token_response.text)
	result["access_token"] = tokens['access_token'];
```
, pack("authUrl", "https://login.microsoftonline.com/c7756af4-456c-451f-8021-93fb18c3f71b/oauth2/v2.0/token", "secret", h"x~", "client_id", "7ef08d46-2833-4fbd-b3e9-df030f844b37", "scope", "https://crm.crm6.dynamics.com/.default")
)
````

When I run this I get an exception.

````
 Query execution has resulted in error (0x80131500): Partial query failure: 0x80131500 (message: 'Encountered an error during execution of local sandbox. Error details: Python code execution failed with the following error: ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /c7756af4-456c-451f-8021-93fb18c3f71b/oauth2/v2.0/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000B102BD908>: Failed to establish a new connection: [WinError 10050] A socket operation encountered a dead network',)); Traceback (most recent call last):
  File "D:\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "D:\lib\site-packages\urllib3\util\connection.py", line 83, in create_connection
    raise err
  File "D:\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [WinError 10050] A socket operation encountered a dead network

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "D:\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "D:\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "D:\lib\site-packages\urllib3\connection.py", line 284, in connect
    conn = self._new_conn()
  File "D:\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0000000B102BD908>: Failed to establish a new connection: [WinError 10050] A socket operation encountered a dead network

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\lib\site-packages
equests\adapters.py", line 440, in send
    timeout=timeout
  File "D:\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\lib\site-packages\urllib3\util
etry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /c7756af4-456c-451f-8021-93fb18c3f71b/oauth2/v2.0/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000B102BD908>: Failed to establish a new connection: [WinError 10050] A socket operation encountered a dead network',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "execute_python.py", line 165, in exec_python
  File "<string>", line 14, in <module>
  File "D:\lib\site-packages
equests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\lib\site-packages
equests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\lib\site-packages
equests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\lib\site-packages
equests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "D:\lib\site-packages
equests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /c7756af4-456c-451f-8021-93fb18c3f71b/oauth2/v2.0/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000B102BD908>: Failed to establish a new connection: [WinError 10050] A socket operation encountered a dead network',))
.  ==> ExecutePluginOperator failure: ', details: 'Source: DataNode
[0]Kusto.Cloud.Platform.Sandbox.Exceptions.SandboxExecutionException: Encountered an error during execution of local sandbox. Error details: Python code execution failed with the following error: ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /c7756af4-456c-451f-8021-93fb18c3f71b/oauth2/v2.0/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000B102BD908>: Failed to establish a new connection: [WinError 10050] A socket operation encountered a dead network',)); Traceback (most recent call last):
  File "D:\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "D:\lib\site-packages\urllib3\util\connection.py", line 83, in create_connection
    raise err
  File "D:\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [WinError 10050] A socket operation encountered a dead network

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "D:\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "D:\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "D:\lib\site-packages\urllib3\connection.py", line 284, in connect
    conn = self._new_conn()
  File "D:\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0000000B102BD908>: Failed to establish a new connection: [WinError 10050] A socket operation encountered a dead network

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\lib\site-packages
equests\adapters.py", line 440, in send
    timeout=timeout
  File "D:\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\lib\site-packages\urllib3\util
etry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /c7756af4-456c-451f-8021-93fb18c3f71b/oauth2/v2.0/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000B102BD908>: Failed to establish a new connection: [WinError 10050] A socket operation encountered a dead network',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "execute_python.py", line 165, in exec_python
  File "<string>", line 14, in <module>
  File "D:\lib\site-packages
equests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\lib\site-packages
equests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\lib\site-packages
equests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\lib\site-packages
equests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "D:\lib\site-packages
equests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /c7756af4-456c-451f-8021-93fb18c3f71b/oauth2/v2.0/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000B102BD908>: Failed to establish a new connection: [WinError 10050] A socket operation encountered a dead network',))
.
Timestamp=2022-08-05T02:10:52.0737662Z
ClientRequestId=KustoWebV2;a3742587-3fb4-4a84-9321-dc35dd818cf8
ActivityId=08ce22d9-80fa-484c-9041-5ceae44cb659
ActivityType=DN.DEQP.EvalPass.Plugin.python
ServiceAlias=NAT
MachineName=KEngine000000
ProcessName=Kusto.WinSvc.Svc
ProcessId=2864
ThreadId=2712
AppDomainName=Kusto.WinSvc.Svc.exe
ActivityStack=(Activity stack: CRID=KustoWebV2;a3742587-3fb4-4a84-9321-dc35dd818cf8 ARID=08ce22d9-80fa-484c-9041-5ceae44cb659 > DN.FE.ExecuteQuery/371e322f-59e4-43e1-8746-1d913204ba43 > DN.DEQP.EvalPass.Plugin.python/32fb90a6-b949-46f0-9c1b-5ffda714ca57)
ErrorCode=
ErrorReason=
ErrorMessage=
DataSource=
DatabaseName=
ClientRequestId=
ActivityId=00000000-0000-0000-0000-000000000000
Details=Python code execution failed with the following error: ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /c7756af4-456c-451f-8021-93fb18c3f71b/oauth2/v2.0/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000B102BD908>: Failed to establish a new connection: [WinError 10050] A socket operation encountered a dead network',)); Traceback (most recent call last):
  File "D:\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "D:\lib\site-packages\urllib3\util\connection.py", line 83, in create_connection
    raise err
  File "D:\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [WinError 10050] A socket operation encountered a dead network

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "D:\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "D:\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "D:\lib\site-packages\urllib3\connection.py", line 284, in connect
    conn = self._new_conn()
  File "D:\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0000000B102BD908>: Failed to establish a new connection: [WinError 10050] A socket operation encountered a dead network

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\lib\site-packages
equests\adapters.py", line 440, in send
    timeout=timeout
  File "D:\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\lib\site-packages\urllib3\util
etry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /c7756af4-456c-451f-8021-93fb18c3f71b/oauth2/v2.0/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000B102BD908>: Failed to establish a new connection: [WinError 10050] A socket operation encountered a dead network',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "execute_python.py", line 165, in exec_python
  File "<string>", line 14, in <module>
  File "D:\lib\site-packages
equests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\lib\site-packages
equests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\lib\site-packages
equests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\lib\site-packages
equests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "D:\lib\site-packages
equests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /c7756af4-456c-451f-8021-93fb18c3f71b/oauth2/v2.0/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000B102BD908>: Failed to establish a new connection: [WinError 10050] A socket operation encountered a dead network',))


   at Kusto.DataNode.QueryService.PluginsV2.SandboxedPluginBase.ExecuteInSandbox(SandboxKind sandboxKind, ISandboxManager sandboxManager, ClientRequestProperties clientRequestProperties, IDictionary`2 argumentsPropertyBag, IStreamSource inputStreamSource, IDictionary`2 externalArtifacts, Boolean spillToDisk, OperationStatistics& operationStatistics) in C:\source\Src\Engine\DataNode\QueryService\PluginsV2\DistributedPlugins\SandboxedPluginBase.cs:line 61
   at Kusto.DataNode.QueryService.PluginsV2.ScriptExecutionPluginBase.Execute(QueryPluginExecutionContext executionContext, PluginDistributionCapsule distributionCapsule, ClientRequestProperties clientRequestProperties, IStreamSource inputStreamSource, OperationStatistics& operationStatistics) in C:\source\Src\Engine\DataNode\QueryService\PluginsV2\DistributedPlugins\Languages\ScriptExecutionPluginBase.cs:line 167
   at Kusto.DataNode.DataEngineQueryPlan.DataEngineQueryProcessor.DataEngineQueryCallback.ExecutePluginOperator(String pluginName, DataSourceStreamFormat inputStreamFormat, DataSourceStreamFormat outputStreamFormat, String pluginSerializedContext, String serializedQueryContextProperties, IStreamSource inputStream, OperationStatistics& operationStatistics) in C:\source\Src\Engine\DataNode\QueryService\DataEngineQueryPlan\DataEngineQueryProcessor.cs:line 501').

 clientRequestId: KustoWebV2;a3742587-3fb4-4a84-9321-dc35dd818cf8
````

Is this kind of request blocked in the Sandbox?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1dc0c9f-5768-5404-426b-64fe17b5c3ff
* Version Independent ID: 8ca6e09c-861d-429b-8957-0bd065902280
* Content: [Python plugin - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/pythonplugin?pivots=azuredataexplorer)
* Content Source: [data-explorer/kusto/query/pythonplugin.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/pythonplugin.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by ShaikMaheer-MSFT** [comment]
@rajyraman Thanks for the question. GitHub forum is dedicated for docs related issues. For any technical queries or clarifications, we encourage to utilise Microsoft Q & A platform. Kindly raise your query on [Microsoft Q&A Platform](https://docs.microsoft.com/en-us/answers/index.html).

**Comment by rajyraman** [comment]
@ShaikMaheer-MSFT - This is a  docs question. Because, the doc page does not mention anything about any limitation to the python code that can be run inside the python plugin, but the code does not run, even though it is valid. If outbound requests are blocked, this should be documented.

**Comment by ShaikMaheer-MSFT** [comment]
@rajyraman Thanks for sharing more clarity on feedback.

@shsagir Could you please validate feedback and enhance doc as appropriate? Thank you.

**Comment by YaelSchuster** [comment]
Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by adieldar** [comment]
@rajyraman, it is mentioned in the sandbox document "Network: A sandbox can't interact with any resource on the virtual machine (VM) or outside of it.", but I agree it should be clarified more explicitly. We will update the relevant docs.

**Comment by rajyraman** [comment]
@adieldar - I just read through https://docs.microsoft.com/en-us/azure/data-explorer/kusto/concepts/sandboxes#sandbox-parameters. Makes sense.
