### ISSUE TITLE
Unable to get the sample to work

### ISSUE THREAD

**Issue by karthik25** [MicrosoftDocs/dataexplorer-docs#207]
Hello,

I have a data explorer resource that has a database and a table w/ ~ 600k rows. I am trying to use this `KustoClientFactory.CreateCslQueryProvider` to execute a query but I cannot seem to get it to work. It fails with the following exception. While I understand that its failing because something is missing in the instance of `KustoConnectionStringBuilder` passed, what actually it is is not clear. Any pointers might help. 

```
Unhandled exception. System.ArgumentException: str (Parameter 'Argument 'str' is empty: at DeserializeObjectFromString in C:\TFS\Kusto\Main\Src\Common\Kusto.Cloud.Platform\Json\ExtendedJson.cs: line 58')
   at Kusto.Cloud.Platform.Utils.Ensure.ArgIsNotNullOrWhiteSpace(String value, String argName, String callerMemberName, String callerFilePath, Int32 callerLineNumber)
   at Kusto.Cloud.Platform.Json.ExtendedJson.DeserializeObjectFromString[T](String str, JsonSerializerSettings settings)   at Kusto.Cloud.Platform.Http.AadHttpClientAuthenticator.GetUserTokenByPasswordAsync(String username, String password, String tenantId, String resourceId, String clientId)
   at Kusto.Cloud.Platform.Http.AadHttpClientAuthenticator.GetUserTokenAsync()
   at Kusto.Cloud.Platform.Http.AadHttpClientAuthenticator.RunProtectedFromCacheCorruptionAsync[T](Func`1 acquireTokenAsync)
   at Kusto.Cloud.Platform.Http.AadHttpClientAuthenticator.GetTokenAsync()
   at Kusto.Cloud.Platform.Utils.ExtendedTask.ResultEx[TResult](Task`1 task)
   at Kusto.Cloud.Platform.Http.AadHttpClientAuthenticator.<AuthenticateAsync>b__22_0()
   at Kusto.Cloud.Platform.Utils.ExceptionFilters.<>c__DisplayClass2_0`1.<RunTraceRethrow>b__0()
   at Kusto.Cloud.Platform.Utils.ExceptionFiltersCodeGenerator.TryFilterCatch_Neutered(Action tryBlock, Func`2 filterBlock, Action`1 catchBlock)
   at Kusto.Cloud.Platform.Utils.ExceptionFiltersCodeGenerator.TryFilter(Action tryBlock, Action`1 filterBlock)
   at Kusto.Cloud.Platform.Utils.ExceptionFilters.RunTraceRethrow[TResult](Func`1 runAction, String faultTraceMessage, ITraceSource tracer, String callerMemberName, String callerFilePath, Int32 callerLineNumber)
   at Kusto.Cloud.Platform.Utils.AsyncInvoker.AsyncInvokerCapsuleFunc`1.TaskTrampolineFunc()   
   ---snip---
```

Given below is the source method:

```csharp
       private static void VerifyData(string userPassword)
        {
            var tenantId = "https://login.windows.net/<my-tenant-id>/oauth2/authorize";
            var user = "<my-user-id>";
            var password = userPassword;
            var kustoUri = "https://<my-kusto-url>.eastus2.kusto.windows.net:443/";
            var database = "<my-kusto-db>";

            var kustoConnectionStringBuilder =
                new KustoConnectionStringBuilder(kustoUri)
                {
                    FederatedSecurity = true,
                    InitialCatalog = database,
                    UserID = user,
                    Password = password,
                    Authority = tenantId
                };

            var table = "nygreentaxi";

            using (var cslQueryProvider = KustoClientFactory.CreateCslQueryProvider(kustoConnectionStringBuilder))
            {
                var query = $"{table} | limit 10";
                var clientRequestProperties = new ClientRequestProperties() { ClientRequestId = Guid.NewGuid().ToString() };
                
                using (var reader = cslQueryProvider.ExecuteQuery(query, clientRequestProperties))
                {
                    while (reader.Read())
                    {
                        var firstCol = reader.GetString(0);
                        Console.WriteLine($"{firstCol}");
                    }
                }
            }
        }
```

I was able to get `ExecuteQuery` and ingestion work using the .net framework packages and the `WithAadUserPromptAuthentication()` method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae82ebd2-f7f6-5068-54f2-69c7532b6b38
* Version Independent ID: 4727dbed-4e17-879b-d494-6ee62d78633a
* Content: [Ingest data with Azure Data Explorer .NET Standard SDK (Preview)](https://docs.microsoft.com/en-us/azure/data-explorer/net-standard-ingest-data)
* Content Source: [data-explorer/net-standard-ingest-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/net-standard-ingest-data.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@karthik25  Thanks for the question! We are investigating and will update you shortly.

**Comment by orspod** [comment]
@karthik25 we are in the process of fixing this doc. PR#https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/650.

**Comment by orspod** [comment]
@karthik25 - thanks again for your feedback and for alerting us to issues with the doc. The doc has been revamped. See: https://docs.microsoft.com/en-us/azure/data-explorer/net-sdk-ingest-data . I will now close this issue. If you have additional problems, feel free to open a new issue or comment here.
